### PR TITLE
Add auto-detection of compiler versions

### LINKED ISSUE #1: Show versions of compilers
Currently, the drop down shows the hardcoded versions of the compilers.

Screenshot 2023-10-05 at 8 51 32 AM

We need the actual version of compilers.

### PR DESCRIPTION
**Pull request by Aqua-16**
## Description

I have modified the code to extract the compiler version most recently used by the user from the system and display it, instead of the hardcoded versions. While testing, I also faced an issue with the `python3` command on a couple of different systems, so I generalized it to `py -3`. This works completely fine on all systems I have tested on.

## Related Issue

Fixes #1 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shank03** [comment]
Screenshot 2023-10-28 at 1 22 28 PM

Well, I wouldn't want so much information just to confuse myself between `gcc` and `g++`. Also, `py` commands are not necessary to be available or installed by the user.
Maybe the first line of any `--version` output should be enough.

**Comment by Aqua-16** [comment]
Sir I tried running both the python and the py commands on a fresh system with just python installed and the python command gave an error code of 9009. The py on the other hand worked smoothly.

image
image

**Comment by shank03** [comment]
I get`code = 127` on `py` but works for `python`. `python` should work all the time, you need additional setup for `py` to work

**Comment by Aqua-16** [comment]
I'll change it to `python3` and `python2` then. But I have no idea why they don't work for me. Just `python` works, but that won't give the different versions.

**Review by shank03 — APPROVED** [review]

**Pull request merged**
